export const AUTH_CONSTRAINTS = {
    EMAIL_MAX_LENGTH: 254,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 72,
    REGISTER_RATE_LIMIT_MAX_ATTEMPTS: 4,
    REGISTER_RATE_LIMIT_WINDOW_SECONDS: 3600,
    LOGIN_RATE_LIMIT_MAX_ATTEMPTS: 5,
    LOGIN_RATE_LIMIT_WINDOW_SECONDS: 900,
};

export const URL_CONSTRAINTS = {
    CODE_MAX_LENGTH: 32,
    SHORT_CODE_LENGTH: 7,
    CREATE_URL_RETRY_LIMIT: 3,
    ALIAS_MIN_LENGTH: 3,
    ALIAS_MAX_LENGTH: 50,
};
